<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\TechAvail.Core\TechAvail.Core.csproj" />
    <ProjectReference Include="..\..\src\TechAvail.Data\TechAvail.Data.csproj" />
  </ItemGroup>

</Project>
